### ISSUE TITLE
Example not working?

### ISSUE THREAD

**Issue by sueswe** [Qurasoft/teams_connector#5]
Hi there,
thank you for your awesome work.

I have a little problem here: the test_card works perfectly with out Teams-Channel.
But the following does not work for me:

  # Send a card with a list of facts
  content = {
    title: "Teams Connector Readme",
    subtitle: "A list of facts",
    facts: {
      "Usage": "Testing the facts Card"
    }
  }
  TeamsConnector::Notification::Message.new(:facts_card, "This is a summary", content).deliver_later

C:/Users/username/.gem/gems/teams_connector-0.1.5/templates/teams_connector/facts_card.json.erb:11:in `deliver_later': undefined method `present?' for {:Usage=>"Testing the facts Card"}:Hash (NoMethodError)
        from C:/SVSW/Ruby/lib/ruby/2.7.0/erb.rb:905:in `eval'
        from C:/SVSW/Ruby/lib/ruby/2.7.0/erb.rb:905:in `result'
        from C:/Users/username/.gem/gems/teams_connector-0.1.5/lib/teams_connector/notification.rb:21:in `deliver_later'
        from tc.rb:23:in `<main>'

Do you have any ideas or tips?

Thank you!

--Werner.

**Comment by ghost** [comment]
Hello Werner,

Thank you for using our gem.
In our projects we use the `TeamsConnector` alsways in conjunction with Rails. Rails extends the ruby core Object with some useful methods. One of them is [`#present?`](https://github.com/rails/rails/blob/174ab6c342b5bb560dfb5d15bba44f89aa1c0bed/activesupport/lib/active_support/core_ext/object/blank.rb#L22).
As a quick fix we suggest you to use define this simple extension to object yourself. But since we want `TeamsConnector` not to rely on too many external features, we will post an update soon that does not use `present?`.

Regards
Lucas

**Comment by sueswe** [comment]
Thank you very much.

> Hello Werner,
> 
> Thank you for using our gem. In our projects we use the `TeamsConnector` alsways in conjunction with Rails. Rails extends the ruby core Object with some useful methods. One of them is [`#present?`](https://github.com/rails/rails/blob/174ab6c342b5bb560dfb5d15bba44f89aa1c0bed/activesupport/lib/active_support/core_ext/object/blank.rb#L22). As a quick fix we suggest you to use define this simple extension to object yourself. But since we want `TeamsConnector` not to rely on too many external features, we will post an update soon that does not use `present?`.
> 
> Regards Lucas
